#spring:
#  application:
#    name: users
#  cloud:
#    config:
<<<<<<< HEAD
#      uri: http://localhost:8888
=======
#      uri: http://localhost:8888
>>>>>>> eda5a1c767375917a3993b8d6c8e700773e64225
