server:
  port: 9090

zuul:
  prefix: /api
  routes:
      owners:
        stripPrefix: false
        url: http://owners:8081
      pets:
        stripPrefix: false
        url: http://owners:8082
      comments:
        stripPrefix: false
        url: http://owners:8083
