server:
  port: 9090

zuul:
  prefix: /api
  routes:
      users:
        serviceId: pets
        path: /api/owners/*/pets/**
        stripPrefix: false
      pets:
         serviceId:pets
         path: /api/foo/**
         stripPrefix: false
      owners:
          serviceId: owners
          path: /api/owners/**
          stripPrefix: false
